fieldLayouts:
  5f2c153f-a494-4e4b-8786-d07e2baf27e6:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 8b5f48b3-0162-4c02-90d6-6817c33edab9
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: adb74c20-f54a-4abb-b3bd-8ffa32a3c8d4
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 1fb66b9e-4d21-40da-a6bc-1097d6e2134f
            required: true
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: '1'
handle: homepage
hasTitleField: '1'
name: Homepage
section: 78655d6a-d7e5-4e30-96a6-e486b0201626 # Homepage
sortOrder: '1'
titleFormat: null
