field: 6a41b799-6ade-45e7-824d-4287f9599224
fieldLayouts:
  c541f1b6-a00a-43bc-814e-b84540a7c9f4:
    tabs:
      -
        fields:
          2ec34254-86b0-4832-9a8a-a188f6c224c5:
            required: '0'
            sortOrder: '1'
        name: Content
        sortOrder: '1'
fields:
  2ec34254-86b0-4832-9a8a-a188f6c224c5:
    contentColumnType: text
    fieldGroup: null
    handle: bodytext
    instructions: ''
    name: bodyText
    searchable: '1'
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: '1'
