contentColumnType: string
fieldGroup: b8b97f8e-826c-4337-92cb-658228f33b21
handle: author
instructions: ''
name: Author
searchable: '1'
settings:
  limit: '1'
  localizeRelations: false
  selectionLabel: 'Add Author'
  sources: '*'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Users
