contentColumnType: string
fieldGroup: b8b97f8e-826c-4337-92cb-658228f33b21
handle: featureImage
instructions: ''
name: 'Feature Image'
searchable: '1'
settings:
  allowedKinds: null
  defaultUploadLocationSource: 'volume:c74e26c0-a5a9-474b-bc3b-7a1897653e53'
  defaultUploadLocationSubpath: ''
  limit: '8'
  localizeRelations: false
  restrictFiles: ''
  selectionLabel: 'Add Image'
  singleUploadLocationSource: 'volume:ad0ca7cb-6c5e-4abe-908d-18513dd2c042' # Feature Image
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: '1'
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
