contentColumnType: string
fieldGroup: b8b97f8e-826c-4337-92cb-658228f33b21
handle: postCategory
instructions: ''
name: 'Post Category'
searchable: '1'
settings:
  branchLimit: ''
  localizeRelations: false
  selectionLabel: 'Add Tag'
  source: 'group:ca37695f-c940-4b2c-aa8e-bd99d93331fb'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
