enableVersioning: '1'
handle: blog
name: 'Blog Post'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  831a6d2e-df54-465d-9476-ea529c12f2c3:
    enabledByDefault: '1'
    hasUrls: '1'
    template: blog/_entry
    uriFormat: 'blog/{slug}'
type: channel
