enableVersioning: '1'
handle: blogIndex
name: 'Writing & Talks'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  831a6d2e-df54-465d-9476-ea529c12f2c3:
    enabledByDefault: '1'
    hasUrls: '1'
    template: blog/index
    uriFormat: blog
type: single
